on:
  workflow_call:

name: Analyze and test

jobs:
  analyze-test:
    runs-on: ubuntu-latest
    continue-on-error: true
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: "3.x"
          channel: "stable"
          cache: true
          cache-key: "deps-${{ hashFiles('**/pubspec.lock') }}"
          cache-path: ${{ runner.tool_cache }}/flutter # optional, change this to specify the cache path

      - name: Setup environment variables
        env:
          CAPTCHA_TOKEN: ${{ secrets.CAPTCHA_TOKEN }}
          API_KEY: ${{ secrets.API_KEY }}
          APP_ID: ${{ secrets.APP_ID }}
          MESSAGE_SENDER_ID: ${{ secrets.MESSAGE_SENDER_ID }}
          PROJECT_ID: ${{ secrets.PROJECT_ID }}
        run: |
          echo "CAPTCHA_TOKEN=$CAPTCHA_TOKEN" >> .env
          echo "API_KEY=$API_KEY" >> .firebase.env
          echo "APP_ID=$APP_ID" >> .firebase.env
          echo "MESSAGE_SENDER_ID=$MESSAGE_SENDER_ID" >> .firebase.env
          echo "PROJECT_ID=$PROJECT_ID" >> .firebase.env

      - name: Download dependencies
        run: flutter pub get

      - name: Analyze
        uses: zgosalvez/github-actions-analyze-dart@v1

      - name: Test
        run: |
          flutter test -r json > test-report.json

      - name: Upload test reports
        if: success() || failure() # Always upload report
        uses: dorny/test-reporter@v1
        with:
          name: Flutter Tests
          path: "*.json"
          reporter: flutter-json
          only-summary: "true"
