on:
  workflow_call:

name: Analyze and test

jobs:
  analyze-and-test:
    name: Analyze and test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      # We use the pubspec as the cache key to detect dependencies changes
      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: "2.10.x"
          channel: "stable"
          cache: true
          cache-key: deps-${{ hashFiles('pubspec.lock') }} # optional, change this to force refresh cache
          cache-path: ${{ runner.tool_cache }}/flutter # optional, change this to specify the cache path

      - name: Setup environment variables
        run: |
          echo "CAPTCHA_TOKEN=${{ secrets.CAPTCHA_TOKEN }}" >> .env
          echo "API_KEY=${{ secrets.API_KEY }}" >> .firebase.env
          echo "APP_ID=${{ secrets.APP_ID }}" >> .firebase.env
          echo "MESSAGE_SENDER_ID=${{ secrets.MESSAGE_SENDER_ID }}" >> .firebase.env
          echo "PROJECT_ID=${{ secrets.PROJECT_ID }}" >> .firebase.env

      - name: Get the dependencies
        run: flutter pub get

      - name: Analyze
        run: flutter analyze --no-fatal-infos --no-fatal-warnings

      - name: Test
        run: flutter test
        continue-on-error: true
